import type { ActionName } from '@shared/domain/assistant'

export const DIFFICULT_SCENARIOS = new Set([
  '5.5',
  '6.8',
  '6.12',
  '9.6',
  '10.6',
  '12.6',
  '14.1',
  '14.3',
  '15.5',
  '15.6',
  '17.2',
  '17.3',
  '17.4',
  '18.1',
  '21.2',
  '22.4',
  '23.3',
  '24.2',
  '24.4',
  '24.5',
  '24.9',
  '33.1',
  '39.2',
  '40.4',
  '42.2',
  '43.1',
  '44.4',
  '45.3',
  '46.1',
  '46.4',
  '48.2',
  '48.3',
  '49.7',
  '50.2',
  '50.6',
  '50.7',
  '51.8',
  '54.5',
  '55.9',
  '55.10',
  '55.11',
  '56.6',
  '56.7',
  '57.3',
  '58.6',
  '58.8',
  '58.9',
  '58.16',
  '58.23',
  '61.13',
  '66.1',
  '66.2',
  '66.4',
  '68.4',
  '68.6',
])

export const CONTROL_CASES: readonly { request: string; expectedAction: ActionName }[] = [
  { request: 'make the selected object disappear from view', expectedAction: 'node.setVisible' },
  { request: 'masque temporairement cet élément', expectedAction: 'node.setVisible' },
  { request: 'change the filename without moving it', expectedAction: 'file.rename' },
  {
    request: 'rends ce calque à moitié transparent',
    expectedAction: 'layer.setOpacityBlendAndVisibility',
  },
  { request: 'garde cette préférence en mémoire pour ce projet', expectedAction: 'memory.write' },
  { request: 'show me whether this repository has pending changes', expectedAction: 'git.status' },
  {
    request: 'déclenche cet évènement à la cinquième seconde',
    expectedAction: 'timeline.addSceneCue',
  },
  { request: 'how many media assets are in this project', expectedAction: 'assets.counts' },
  { request: 'explain what this selected object contains', expectedAction: 'studio.describe' },
  {
    request: 'change the values of this gameplay component',
    expectedAction: 'component.setProperties',
  },
  {
    request: 'agrandis la zone de dessin sans toucher aux calques',
    expectedAction: 'canvas.resize',
  },
  { request: 'turn this post-processing effect off', expectedAction: 'post.setEffectEnabled' },
]
