import { describe, expect, it } from 'vitest'
import type { Licence } from './domain/licence'
import licences from './licences.json'

/**
 * The sixth way a word reaches the screen, and the one no AST guard can see.
 *
 * The five guards of the repository read TypeScript. `licences.json` is generated by
 * `pnpm licences:collect` and rendered verbatim by the Licences window, so a sentence written
 * into it by the script lands on screen having passed no bundle at all — which is how
 * "shipped with the application" and "— version 1.52.3, unmodified" were read by French users.
 *
 * The fields below are drawn beside translated labels. `text` is not among them: a licence is
 * reproduced word for word, in the language its authors wrote it.
 */
describe('licences.json', () => {
  const entries: Licence[] = licences

  it('lists what the studio ships', () => {
    expect(entries.length).toBeGreaterThan(30)
  })

  // A version numbers itself. Anything with a space in it is a sentence about the version.
  it('numbers a version rather than describing it', () => {
    const described = entries.filter(entry => entry.version?.includes(' '))

    expect(described.map(entry => `${entry.name}: ${entry.version}`)).toEqual([
      // FFmpeg alone ships two builds at once, and the slash is what separates them.
      'FFmpeg: 7.1.1 / 7.1.5',
    ])
  })

  /**
   * `sources` is a URL, or one URL per line. Prose around it — "unmodified", "version 1.52.3" —
   * is the window's business, and the window has two keys for it.
   */
  it('offers a source as a link, never as a sentence about one', () => {
    const spoken = entries
      .flatMap(entry => (entry.sources ?? '').split('\n').map(line => ({ entry, line })))
      .filter(({ line }) => line !== '' && !/^(ffmpeg [\d.]+: )?https?:\/\/\S+$/.test(line))

    expect(spoken.map(({ entry, line }) => `${entry.name}: ${line}`)).toEqual([])
  })

  // The offer is what copyleft asks for: a component owing one and carrying none fails the build
  // in `collect-licences.mjs`, and this says the same thing from the side that ships.
  it('marks an unmodified redistribution only where it offers the source', () => {
    const claimed = entries.filter(entry => entry.unmodified)

    expect(claimed.every(entry => entry.sources)).toBe(true)
    expect(claimed.length).toBeGreaterThan(0)
  })
})
