import { describe, expect, it } from 'vitest'
import { NO_VERSION, type Licence } from './domain/licence'
import { TRANSLATIONS } from './i18n'
import licences from './licences.json'

/**
 * The sixth way a word reaches the screen, and the one no AST guard can see.
 *
 * The five guards of the repository read TypeScript. `licences.json` is generated by
 * `pnpm licences:collect` and rendered verbatim by the Licences window, so a sentence written
 * into it by the script lands on screen having passed no bundle at all — which is how
 * "shipped with the application" and "— version 1.52.3, unmodified" were read by French users.
 *
 * `text` is exempt: a licence is reproduced word for word, in the language its authors wrote it.
 */
const PROSE = /\p{Letter}{2,}\s+\p{Letter}{2,}/u

/** A link, optionally announced by the build it belongs to — never a sentence around one. */
const LINK = /^([\w.]+ [\d.]+: )?https?:\/\/\S+$/

describe('licences.json', () => {
  const entries: Licence[] = licences

  // Pinned rather than merged: the notice must read on its own, the bundle is what the window
  // translates. Reworded on one side alone, the two would drift in silence.
  it('says the same thing in the notice and in the window', () => {
    expect(NO_VERSION).toBe(TRANSLATIONS.en.licences.bundled)
  })

  // Two words running together are prose, whatever the numbering around them: FFmpeg ships two
  // builds as `7.1.1 / 7.1.5` and passes, where `shipped with the application` cannot.
  it('numbers a version rather than describing it', () => {
    const described = entries.filter(entry => PROSE.test(entry.version ?? ''))

    expect(described.map(entry => `${entry.name}: ${entry.version}`)).toEqual([])
  })

  it('offers a source as a link, never as a sentence about one', () => {
    const spoken = entries
      .flatMap(entry => (entry.sources ?? '').split('\n'))
      .filter(line => line !== '' && !LINK.test(line))

    expect(spoken).toEqual([])
  })

  // The canary the three tests above rest on: a file that lost its offers would pass them all.
  it('still carries the offer copyleft asks for', () => {
    const claimed = entries.filter(entry => entry.unmodified)

    expect(claimed.every(entry => entry.sources)).toBe(true)
    expect(claimed.length).toBeGreaterThan(0)
  })
})
