import { describe, expect, it } from 'vitest'
import { LANGUAGES, type Language } from './i18n/languages'
import { deadManualLinks, type ManualChapter } from './domain/manual'
import { americanVerbs, americanWords, proseOf } from './i18n/spelling-fixtures'
import { TRANSLATIONS } from './i18n'
import { isRecord } from './guards'
import manual from './manual.json'

/**
 * The seventh way a word reaches the screen, after the six `licences.i18n.test.ts` names.
 *
 * `manual.json` is generated by `pnpm manual:collect` and rendered verbatim by the Help ▸ User
 * manual window: every sentence of it lands on screen having passed no bundle. Which is right —
 * it IS the manual, written in `docs/` in both languages — but it means nothing else guards it.
 *
 * Freshness is the one thing not checked here: it needs the filesystem, and lives in
 * `main/manual.test.ts` for the reason `main/licences.test.ts` gives.
 */
const languages = LANGUAGES.map(language => language.code)

/** Per language, never merged: `07-assets` is the slug of a chapter in BOTH — see `ManualChapter`. */
const chaptersOf = (language: (typeof languages)[number]): ManualChapter[] => manual[language]

/**
 * Both separators the chapters write, and they are not interchangeable to a regexp: `▸` carries
 * 70 paths in French and 71 in English, `›` four each. Reading one alone missed two false
 * citations, measured.
 *
 * Bounded and newline-free because `**` pairs greedily across a paragraph: an unbounded reading
 * returned whole sentences as menu paths, which is a relevé nobody can act on.
 */
const MENU_PATH = /\*\*([^*\n]{1,90}[▸›][^*\n]{1,90})\*\*/g

/** As a reader compares a quote to a menu: trailing ellipsis dropped, holes dropped, folded. */
const asRead = (text: string): string =>
  text
    .replace(/\{\{[^}]*\}\}/g, '')
    .replace(/[….]+$/, '')
    .trim()
    .toLowerCase()

const labelsOf = (bundle: unknown, into = new Set<string>()): Set<string> => {
  if (typeof bundle === 'string') into.add(asRead(bundle))
  else if (isRecord(bundle)) for (const held of Object.values(bundle)) labelsOf(held, into)

  return into
}

/**
 * Segments that follow the shape of a path without naming a menu entry. One each, and both are
 * the same thing: a GESTURE the chapter puts before the entry it opens.
 */
const NOT_A_MENU_ENTRY: Record<Language, ReadonlySet<string>> = {
  fr: new Set(['clic droit']),
  en: new Set(['right-click']),
}

describe('the manual the application carries', () => {
  // A hole here is a language that opens on nothing, and only for the readers who chose it.
  it('carries the same chapters in every language', () => {
    const reference = chaptersOf('fr').map(chapter => chapter.number)

    expect(reference.length).toBeGreaterThan(0)
    for (const language of languages) {
      expect(chaptersOf(language).map(chapter => chapter.number)).toEqual(reference)
    }
  })

  /**
   * What is written for someone browsing the repository must not reach a reader: the
   * `[← …] · [Contents] · [Next →]` rows are a GitHub necessity the window replaces, and
   * `<!-- CAPTURE … -->` is a note to whoever will take the screenshot one day.
   */
  it('leaves the scaffolding of the repository behind', () => {
    const leaked = languages.flatMap(language =>
      chaptersOf(language)
        .filter(chapter => /CAPTURE|guide-utilisateur|user-guide/.test(chapter.markdown))
        .map(chapter => `${language}/${chapter.slug}`),
    )

    expect(leaked).toEqual([])
  })

  /**
   * Asked of the SHIPPED data, with the same predicate the collector asks of what it is about to
   * write: the collector proves what it wrote at the moment it wrote it, and this file is what
   * the window actually opens.
   */
  it('has no link that goes nowhere', () => {
    const dead = languages.flatMap(language => deadManualLinks(chaptersOf(language), language))

    expect(dead).toEqual([])
  })

  /**
   * The English bundle is British throughout, and `bundles.test.ts` holds it there. The manual
   * quotes those same labels and explains them in prose, so a chapter written American reads as a
   * second spelling of the product — which is what the bundle's own `Vectorization` was, sitting
   * beside the `vectorisation` these chapters already spelled.
   *
   * Prose only, and `proseOf` says what that costs: the `Authorization` header of two chapters
   * would fail this guard on its first run.
   *
   * What it does not read: the French chapters, which have no British side to keep, and the two
   * pairs `AMERICAN_FORMS` leaves out, where British English spells both words.
   */
  it('spells its English prose the British way', () => {
    const american = chaptersOf('en').flatMap(chapter => {
      const prose = `${chapter.title}\n${proseOf(chapter.markdown)}`

      return [...americanVerbs(prose), ...americanWords(prose)].map(
        word => `${chapter.slug} — ${word}`,
      )
    })

    expect(american).toEqual([])
  })

  /**
   * A chapter sending its reader to **Help ▸ Journal** was sending them to a menu entry no
   * language carries, and the manual being read INSIDE the window, a wrong path reads as the
   * software being broken. The French chapters were right to the last of their 66 paths; the
   * English ones held ten wrong citations — `Export the scene` for `Export scene`, `Enlarge` for
   * `Upscale` — the shape of a manual translated from the French without re-reading the English
   * screen.
   *
   * What it does NOT read, and it is most of the quoting: a label written on its own, outside a
   * path. `**Enlarge**` alone sat in three more chapters and no reading here would have found it.
   */
  it.each(languages)('quotes no menu path the screen does not carry, in %s', language => {
    const labels = labelsOf(TRANSLATIONS[language])
    const invented = chaptersOf(language).flatMap(chapter =>
      [...chapter.markdown.matchAll(MENU_PATH)]
        // The group always matches — `flatMap` drops the `[]` the type demands.
        .flatMap(match => match[1] ?? [])
        .flatMap(path =>
          path
            .split(/[▸›]/)
            .map(asRead)
            .filter(
              segment =>
                segment && !labels.has(segment) && !NOT_A_MENU_ENTRY[language].has(segment),
            )
            .map(segment => `${chapter.slug} — "${segment}" in ${path.trim()}`),
        ),
    )

    expect(invented).toEqual([])
  })

  /**
   * The same reasoning `bundles.test.ts` applies to its own exemptions: one whose segment stopped
   * being written is one nobody would think to delete, and the next reader takes it for a rule.
   */
  it.each(languages)('drops a gesture exemption once no path writes it, in %s', language => {
    const written = new Set(
      chaptersOf(language).flatMap(chapter =>
        [...chapter.markdown.matchAll(MENU_PATH)]
          .flatMap(match => match[1] ?? [])
          .flatMap(path => path.split(/[▸›]/).map(asRead)),
      ),
    )

    expect([...NOT_A_MENU_ENTRY[language]].filter(segment => !written.has(segment))).toEqual([])
  })

  // The range a literal union would have held, had a JSON import been able to keep one.
  it('numbers every heading between one and four', () => {
    const outside = languages.flatMap(language =>
      chaptersOf(language)
        .flatMap(chapter => chapter.headings)
        .filter(entry => !Number.isInteger(entry.depth) || entry.depth < 1 || entry.depth > 4),
    )

    expect(outside).toEqual([])
  })
})
