import { describe, expect, it } from 'vitest'
import { LANGUAGES } from './i18n/languages'
import { deadManualLinks, type ManualChapter } from './domain/manual'
import manual from './manual.json'

/**
 * The seventh way a word reaches the screen, after the six `licences.i18n.test.ts` names.
 *
 * `manual.json` is generated by `pnpm manual:collect` and rendered verbatim by the Help ▸ User
 * manual window: every sentence of it lands on screen having passed no bundle. Which is right —
 * it IS the manual, written in `docs/` in both languages — but it means nothing else guards it.
 *
 * Freshness is the one thing not checked here: it needs the filesystem, and lives in
 * `main/manual.test.ts` for the reason `main/licences.test.ts` gives.
 */
const languages = LANGUAGES.map(language => language.code)

/** Per language, never merged: `07-assets` is the slug of a chapter in BOTH — see `ManualChapter`. */
const chaptersOf = (language: (typeof languages)[number]): ManualChapter[] => manual[language]

describe('the manual the application carries', () => {
  // A hole here is a language that opens on nothing, and only for the readers who chose it.
  it('carries the same chapters in every language', () => {
    const reference = chaptersOf('fr').map(chapter => chapter.number)

    expect(reference.length).toBeGreaterThan(0)
    for (const language of languages) {
      expect(chaptersOf(language).map(chapter => chapter.number)).toEqual(reference)
    }
  })

  /**
   * What is written for someone browsing the repository must not reach a reader: the
   * `[← …] · [Contents] · [Next →]` rows are a GitHub necessity the window replaces, and
   * `<!-- CAPTURE … -->` is a note to whoever will take the screenshot one day.
   */
  it('leaves the scaffolding of the repository behind', () => {
    const leaked = languages.flatMap(language =>
      chaptersOf(language)
        .filter(chapter => /CAPTURE|guide-utilisateur|user-guide/.test(chapter.markdown))
        .map(chapter => `${language}/${chapter.slug}`),
    )

    expect(leaked).toEqual([])
  })

  /**
   * Asked of the SHIPPED data, with the same predicate the collector asks of what it is about to
   * write: the collector proves what it wrote at the moment it wrote it, and this file is what
   * the window actually opens.
   */
  it('has no link that goes nowhere', () => {
    const dead = languages.flatMap(language => deadManualLinks(chaptersOf(language), language))

    expect(dead).toEqual([])
  })

  // The range a literal union would have held, had a JSON import been able to keep one.
  it('numbers every heading between one and four', () => {
    const outside = languages.flatMap(language =>
      chaptersOf(language)
        .flatMap(chapter => chapter.headings)
        .filter(entry => !Number.isInteger(entry.depth) || entry.depth < 1 || entry.depth > 4),
    )

    expect(outside).toEqual([])
  })
})
