import { readText } from '../guards'
import type { ActionName } from './assistantAction'
import type { MemoryRefKind, MemoryType } from './assistantMemory'

/**
 * 🛑 `Record<ActionName, …>`, exactly like `COVERAGE` in `scripts/banc/coverage.ts`: an action
 * added to the registry does not COMPILE until this file has answered what, if anything, is worth
 * remembering about it — `null` being a hole DECLARED rather than one forgotten.
 */

/**
 * What a rule draws, before the window turns it into a memory.
 *
 * A KEY and not a sentence: the summary is shown in Réglages ▸ Mémoire, so it is a word of the
 * interface and the window resolves it in the person's language.
 */
export type MemoryDrawn = {
  type: MemoryType
  summaryKey: string
  /** What fills the holes of the key. Values, never sentences — a path, a name, a message. */
  values: Readonly<Record<string, string>>
  importance: number
  refs?: readonly { kind: MemoryRefKind; ref: string }[]
}

/**
 * `reads` beside the function so a guard can check it: a rule naming a field the action does not
 * declare reads `undefined` for ever, and nothing else in the studio would say so.
 */
export type MemoryRule = null | {
  readonly reads: readonly string[]
  readonly draft: (input: Record<string, unknown>) => MemoryDrawn | null
}

/**
 * The ONE shape all six standing rules share: an action names something, and that name is what is
 * worth remembering.
 *
 * 🛑 The field is named ONCE. Written out, `reads: ['clipName']` sat facing a `textOf(input,
 * 'clipName')` two lines below, and nothing would have said so had the two drifted — that is the
 * very mismatch `reads` exists to let a guard catch. The i18n hole carries the same name for the
 * same reason.
 */
const worthNaming = (
  reads: string,
  type: MemoryType,
  summaryKey: string,
  importance: number,
  anchors?: MemoryRefKind,
): MemoryRule => ({
  reads: [reads],
  draft: input => {
    const named = readText(input, reads)
    return named === null
      ? null
      : {
          type,
          summaryKey,
          values: { [reads]: named },
          importance,
          ...(anchors === undefined ? {} : { refs: [{ kind: anchors, ref: named }] }),
        }
  },
})

export const MEMORY_WORTH: Record<ActionName, MemoryRule> = {
  'command.runStudioCommand': null,
  'workspace.open': null,
  'models.search': null,
  'models.select': null,
  'generator.prepare': null,
  'generator.submit': null,
  'generator.readArmedGeneration': null,
  'jobs.list': null,
  'prompt.suggest': null,
  'prompt.translate': null,
  'prompt.describeStyle': null,
  'chat.close': null,
  'actions.find': null,
  'target.select': null,
  'studio.state': null,
  'documents.list': null,
  'document.open': null,
  'document.activate': null,
  'document.close': null,
  'document.rename': null,
  'document.save': null,
  'document.deleteFromDisk': null,
  'document.export': null,
  'activity.recent': null,
  'projects.list': null,
  'project.open': null,
  'project.close': null,
  'project.create': null,
  'project.forget': null,
  'project.trash': null,
  'file.open': null,
  'files.list': null,
  'files.search': null,
  'files.move': null,
  'files.copy': null,
  'files.duplicate': null,
  'files.trash': null,
  'files.undoFileOperation': null,
  'files.redoFileOperation': null,
  'files.readUndoStack': null,
  'file.rename': null,
  'file.facts': null,
  'file.reveal': null,
  'folder.new': null,
  'project.rename': null,
  'models.readGenerationModelFields': null,
  'cost.estimate': null,
  'job.readCloudGeneration': null,
  'job.waitForCloudGeneration': null,
  'job.cancelCloudGeneration': null,
  'task.cancelLocalTask': null,
  'usage.report': null,
  'assets.searchProjectCatalogue': null,
  'assets.counts': null,
  'assets.absent': null,
  'assets.captionImages': null,
  'asset.get': null,
  'asset.update': null,
  'asset.reveal': null,
  'asset.extractTextures': null,
  'assets.removeFromLibrary': null,
  'canvas.state': null,
  'canvas.resize': null,
  'canvas.setPixelArt': null,
  'canvas.drawPixels': null,
  'canvas.crop': null,
  'canvas.flipOrRotate': null,
  'layer.add': null,
  'layer.remove': null,
  'layer.select': null,
  'layer.rename': null,
  'layer.setOpacityBlendAndVisibility': null,
  'layer.transform': null,
  'layer.editTextLayer': null,
  'layer.reorderInStack': null,
  'layer.duplicate': null,
  'layer.group': null,
  'layer.ungroup': null,
  'layer.mergeDown': null,
  'layer.lock': null,
  'layer.editShapeLayer': null,
  'layer.setAdjustmentAmount': null,
  'layer.setMaskOptions': null,
  'guide.add': null,
  'guide.move': null,
  'guide.remove': null,
  'sequence.state': null,
  'sequence.seek': null,
  'clip.add': null,
  'clip.remove': null,
  'clip.move': null,
  'clip.trim': null,
  'clip.split': null,
  'clip.fade': null,
  'clip.gain': null,
  'clip.speed': null,
  'clip.unlink': null,
  'clip.select': null,
  'track.add': null,
  'track.remove': null,
  'track.reorderTracks': null,
  'track.rename': null,
  'track.setMuteSoloLockHeight': null,
  'skybox.state': null,
  'skybox.setViewOptions': null,
  'skybox.adjustImage': null,
  'skybox.resetAdjustments': null,
  'skybox.setSun': null,
  'skybox.setPreviewLighting': null,
  'skybox.setSourceImage': null,
  'material.state': null,
  'material.setSurfaceSettings': null,
  'material.setPreviewEnvironment': null,
  'material.setPreviewDisplay': null,
  'material.setChannelImage': null,
  'styles.list': null,
  'style.save': worthNaming('name', 'convention', 'memoryWorth.styleSave', 2),
  'style.rename': null,
  'style.remove': null,
  'cloud.browseAccountLibrary': null,
  'cloud.explorePublicFeed': null,
  'cloud.findSimilarPublished': null,
  'cloud.previewSync': null,
  'cloud.pull': null,
  'cloud.push': null,
  'auth.state': null,
  'window.state': null,
  'window.fullScreen': null,
  'settings.open': null,
  'updates.state': null,
  'updates.install': null,
  'dictation.state': null,
  'dictation.start': null,
  'dictation.stop': null,
  'panels.list': null,
  'panel.open': null,
  'panel.close': null,
  'media.capabilities': null,
  'media.indexFileInPlace': null,
  'fonts.list': null,
  'favorites.listPinnedRecipes': null,
  'favorite.pinAssetRecipe': null,
  'favorite.unpinAssetRecipe': null,
  'fileInfo.openWindow': null,
  'mirror.openVideoReturnWindow': null,
  'help.openStudioWindow': null,
  'scene.state': null,
  'node.add': null,
  'node.addModel': null,
  'node.markAsCuttingTool': null,
  'node.combineIntoSolid': null,
  'node.swapSolidMatterAndTool': null,
  'node.separate': null,
  'node.remove': null,
  'node.attach': null,
  'node.rename': null,
  'node.transform': null,
  'node.setVisible': null,
  'node.setMeshMaterial': null,
  'node.setPrimitiveParameters': null,
  'node.setShadowCastAndReceive': null,
  'node.setSpriteSettings': null,
  'node.setTextSettings': null,
  'node.setPathShape': null,
  'path.addPoint': null,
  'path.movePoint': null,
  'path.removePoint': null,
  'node.setLightSettings': null,
  'node.setCameraLens': null,
  'model.wearMaterial': null,
  'model.wearImage': null,
  'camera.addShot': null,
  'camera.bindPathToShot': null,
  'camera.createAndBindPath': null,
  'camera.aimShotAt': null,
  'camera.reorder': null,
  'node.reparent': null,
  'node.select': null,
  'view.direction': null,
  'view.display': null,
  'scene.capture': null,
  'world.applyPreset': null,
  'world.setSceneLighting': null,
  'world.setBackground': null,
  'world.setFog': null,
  'world.setGroundPlane': null,
  'world.setToneMapping': null,
  'post.state': null,
  'post.add': null,
  'post.remove': null,
  'post.move': null,
  'post.set': null,
  'post.setEffectEnabled': null,
  'post.setWholeStackEnabled': null,
  'post.applyPreset': null,
  'post.listPresets': null,
  'post.duplicate': null,
  'post.reset': null,
  'post.key': null,
  'post.unkey': null,
  'post.savePreset': worthNaming('name', 'convention', 'memoryWorth.postSave', 2),
  'post.renamePreset': null,
  'post.deleteSavedPreset': null,
  'post.setCameraStackMode': null,
  'rig.state': null,
  'rig.fit': null,
  'rig.clear': null,
  'rig.hands': null,
  'socket.add': null,
  'socket.remove': null,
  'bone.add': null,
  'bone.remove': null,
  'bone.rename': null,
  'bone.role': null,
  'ik.add': null,
  'ik.remove': null,
  'animations.list': null,
  'animation.addBlock': worthNaming('clipName', 'entity', 'memoryWorth.animationAdd', 2),
  'animation.removeBlock': null,
  'animation.setBlockSettings': null,
  'animation.setBandLengthAndRate': null,
  'animation.autoKey': null,
  'key.writePoseKeys': null,
  'key.removeSubjectKeys': null,
  'key.writeKeysOnOpenChannels': null,
  'key.move': null,
  'channel.remove': null,
  'channel.setMuteSoloLock': null,
  'git.status': null,
  'git.log': null,
  'git.listCommitFiles': null,
  'git.diff': null,
  'git.branches': null,
  'git.stashes': null,
  'git.init': null,
  'git.stage': null,
  'git.unstage': null,
  'git.restore': null,
  /**
   * 🛑 A commit made from the studio leaves the tree DIRTY: this writes to
   * `.ia-studio/memory.ndjson`, which is versioned on purpose — the memory travels with the
   * project — so the version panel shows a change straight after every commit. True of every
   * rule here; this one just makes it visible on the spot.
   */
  'git.commit': worthNaming('message', 'decision', 'memoryWorth.gitCommit', 3),
  'git.createBranch': null,
  'git.checkout': null,
  'git.stash': null,
  'git.stashPop': null,
  'git.tag': null,
  'git.stashDrop': null,
  'git.resolve': null,
  'git.abortMerge': null,
  'git.remotes': null,
  'git.addRemote': null,
  'git.fetch': null,
  'git.pull': null,
  'git.push': null,
  'component.attach': null,
  'component.detach': null,
  'component.set': null,
  'play.start': null,
  'play.stop': null,
  'play.pause': null,
  'play.resume': null,
  'play.step': null,
  'play.loadScene': null,
  'runtime.report': null,
  'runtime.errors': null,
  'script.list': null,
  'script.read': null,
  'script.write': worthNaming('path', 'script', 'memoryWorth.scriptWrite', 4, 'file'),
  'studio.describe': null,
  'studio.docs': null,
  'studio.batch': null,
  'timeline.addSceneCue': null,
  'timeline.removeSceneCue': null,
  'timeline.setPanelRows': null,
  'game.applyTemplate': null,
  'prefab.define': worthNaming('name', 'entity', 'memoryWorth.prefabDefine', 3),
  'prefab.instantiate': null,
  'game.export': null,
  // 🛑 Null for all five, and not by omission: a memory written BY a memory action would be a
  // memory of having written one, and `memory.write` already wrote what was worth keeping.
  'memory.recall': null,
  'memory.read': null,
  'memory.write': null,
  'memory.forget': null,
  'memory.link': null,
  'context.readProjectCards': null,
  'context.writeProjectCard': null,
  'context.deleteProjectCard': null,
  'settings.read': null,
  'settings.write': null,
  'settings.pressButton': null,
  'accounts.list': null,
  'accounts.activate': null,
  'accounts.rename': null,
}
