import { DICTATION_MODES } from './dictation'
import { LOG_VERBOSITIES } from './settings'
import { DISPLAY_UNITS, SHADOW_MAP_SIZES, SHADOW_QUALITIES, VIEWPORT_QUALITIES } from './scene'
import { setting } from './settingDescriptor'

export const SETTING_REGISTRY_SECOND = [
  setting({
    path: 'three.snapRotate',
    kind: 'slider',
    section: 'spaces.three',
    titleKey: 'settings.snapRotate.title',
    helpKey: 'settings.snapRotate.help',
    min: 1,
    max: 90,
    step: 1,
  }),
  setting({
    path: 'three.snapScale',
    kind: 'slider',
    section: 'spaces.three',
    titleKey: 'settings.snapScale.title',
    helpKey: 'settings.snapScale.help',
    min: 0.01,
    max: 1,
    step: 0.05,
  }),
  setting({
    path: 'three.gizmoSize',
    kind: 'slider',
    section: 'spaces.three',
    titleKey: 'settings.gizmoSize.title',
    helpKey: 'settings.gizmoSize.help',
    // Up to twice what the object measures: the cap is a CEILING, and somebody working on a
    // small part wants the handles to stand clear of it rather than hug its outline.
    min: 0.75,
    max: 2,
    step: 0.05,
  }),
  setting({
    path: 'three.snapSurfaceAlign',
    kind: 'boolean',
    section: 'spaces.three',
    titleKey: 'settings.snapSurfaceAlign.title',
    helpKey: 'settings.snapSurfaceAlign.help',
  }),
  setting({
    path: 'three.snapSurfaceOffset',
    kind: 'slider',
    section: 'spaces.three',
    titleKey: 'settings.snapSurfaceOffset.title',
    helpKey: 'settings.snapSurfaceOffset.help',
    min: 0,
    max: 1,
    step: 0.01,
  }),
  setting({
    path: 'three.shadows',
    kind: 'boolean',
    section: 'spaces.three',
    titleKey: 'settings.shadows.title',
    helpKey: 'settings.shadows.help',
  }),
  setting({
    path: 'three.shadowQuality',
    kind: 'choice',
    section: 'spaces.three',
    titleKey: 'settings.shadowQuality.title',
    helpKey: 'settings.shadowQuality.help',
    options: SHADOW_QUALITIES.map(value => ({
      value,
      labelKey: `settings.shadowQuality.${value}`,
    })),
    dependsOn: { path: 'three.shadows', equals: true },
  }),
  setting({
    path: 'three.shadowMapSize',
    kind: 'choice',
    section: 'spaces.three',
    titleKey: 'settings.shadowMapSize.title',
    helpKey: 'settings.shadowMapSize.help',
    // A list rather than a slider: the values in between are not allowed, and a slider would
    // suggest they are.
    options: SHADOW_MAP_SIZES.map(value => ({ value, label: String(value) })),
    dependsOn: { path: 'three.shadows', equals: true },
  }),
  setting({
    path: 'three.quality',
    kind: 'choice',
    section: 'spaces.three',
    titleKey: 'settings.viewportQuality.title',
    helpKey: 'settings.viewportQuality.help',
    options: VIEWPORT_QUALITIES.map(value => ({
      value,
      labelKey: `settings.viewportQuality.${value}`,
    })),
  }),
  setting({
    path: 'three.units',
    kind: 'choice',
    section: 'spaces.three',
    titleKey: 'settings.units.title',
    helpKey: 'settings.units.help',
    options: DISPLAY_UNITS.map(value => ({ value, labelKey: `settings.units.${value}` })),
  }),
  setting({
    path: 'storage.projectsFolder',
    kind: 'path',
    pathKind: 'folder',
    section: 'storage',
    titleKey: 'settings.projectsFolder.title',
    helpKey: 'settings.projectsFolder.help',
  }),
  setting({
    path: 'advanced.logLevel',
    kind: 'choice',
    section: 'advanced',
    titleKey: 'settings.logLevel.title',
    helpKey: 'settings.logLevel.help',
    options: LOG_VERBOSITIES.map(level => ({
      value: level,
      labelKey: `settings.logLevel.${level}`,
    })),
  }),
  setting({
    path: 'dictation.enabled',
    kind: 'boolean',
    section: 'dictation',
    titleKey: 'settings.dictationEnabled.title',
    helpKey: 'settings.dictationEnabled.help',
  }),
  setting({
    path: 'dictation.mode',
    kind: 'choice',
    section: 'dictation',
    titleKey: 'settings.dictationMode.title',
    helpKey: 'settings.dictationMode.help',
    options: DICTATION_MODES.map(mode => ({
      value: mode,
      labelKey: `settings.dictationMode.${mode}`,
    })),
    dependsOn: { path: 'dictation.enabled', equals: true },
  }),
  setting({
    path: 'dictation.silenceMs',
    kind: 'number',
    section: 'dictation',
    titleKey: 'settings.dictationSilence.title',
    helpKey: 'settings.dictationSilence.help',
    min: 200,
    max: 2000,
    step: 50,
    dependsOn: { path: 'dictation.enabled', equals: true },
  }),
  setting({
    path: 'dictation.previewMs',
    kind: 'number',
    section: 'dictation',
    titleKey: 'settings.dictationPreview.title',
    helpKey: 'settings.dictationPreview.help',
    min: 0,
    max: 2000,
    step: 100,
    dependsOn: { path: 'dictation.enabled', equals: true },
  }),
  setting({
    path: 'dictation.threads',
    kind: 'number',
    section: 'dictation',
    titleKey: 'settings.dictationThreads.title',
    helpKey: 'settings.dictationThreads.help',
    min: 1,
    max: 8,
    dependsOn: { path: 'dictation.enabled', equals: true },
  }),
  setting({
    path: 'dictation.idleUnloadMinutes',
    kind: 'number',
    section: 'dictation',
    titleKey: 'settings.dictationIdleUnload.title',
    helpKey: 'settings.dictationIdleUnload.help',
    min: 0,
    max: 120,
    dependsOn: { path: 'dictation.enabled', equals: true },
  }),
  setting({
    path: 'dictation.modelFolder',
    kind: 'path',
    pathKind: 'folder',
    section: 'dictation',
    titleKey: 'settings.dictationModelFolder.title',
    helpKey: 'settings.dictationModelFolder.help',
    placeholderKey: 'settings.dictationModelFolder.placeholder',
    dependsOn: { path: 'dictation.enabled', equals: true },
  }),
  setting({
    path: 'mcp.enabled',
    kind: 'boolean',
    section: 'mcp',
    titleKey: 'settings.mcpEnabled.title',
    helpKey: 'settings.mcpEnabled.help',
  }),
  /**
   * The delegation, and it lives HERE rather than anywhere a client can reach: `settings.write`
   * refuses this branch outright, so the window is the only way in. All four hang off
   * `mcp.enabled` — arming what a closed door may do is a question nobody asked.
   */
  setting({
    path: 'mcp.delegateFiles',
    kind: 'boolean',
    section: 'mcp',
    titleKey: 'settings.mcpDelegateFiles.title',
    helpKey: 'settings.mcpDelegateFiles.help',
    dependsOn: { path: 'mcp.enabled', equals: true },
  }),
  setting({
    path: 'mcp.delegateAsset',
    kind: 'boolean',
    section: 'mcp',
    titleKey: 'settings.mcpDelegateAsset.title',
    helpKey: 'settings.mcpDelegateAsset.help',
    dependsOn: { path: 'mcp.enabled', equals: true },
  }),
  setting({
    path: 'mcp.delegateRemote',
    kind: 'boolean',
    section: 'mcp',
    titleKey: 'settings.mcpDelegateRemote.title',
    helpKey: 'settings.mcpDelegateRemote.help',
    dependsOn: { path: 'mcp.enabled', equals: true },
  }),
  setting({
    path: 'mcp.delegateBudget',
    kind: 'number',
    min: 0,
    max: 10_000,
    step: 1,
    section: 'mcp',
    titleKey: 'settings.mcpDelegateBudget.title',
    helpKey: 'settings.mcpDelegateBudget.help',
    dependsOn: { path: 'mcp.enabled', equals: true },
  }),
  setting({
    path: 'media.ffmpegPath',
    kind: 'path',
    pathKind: 'file',
    section: 'media',
    titleKey: 'settings.ffmpegPath.title',
    helpKey: 'settings.ffmpegPath.help',
    placeholderKey: 'settings.ffmpegPath.placeholder',
  }),
  setting({
    path: 'git.binary',
    kind: 'path',
    pathKind: 'file',
    section: 'git',
    titleKey: 'settings.gitBinary.title',
    helpKey: 'settings.gitBinary.help',
    placeholderKey: 'settings.gitBinary.placeholder',
  }),
  setting({
    path: 'git.userName',
    kind: 'text',
    section: 'git',
    titleKey: 'settings.gitUserName.title',
    helpKey: 'settings.gitUserName.help',
    placeholderKey: 'settings.gitUserName.placeholder',
  }),
  setting({
    path: 'git.userEmail',
    kind: 'text',
    section: 'git',
    titleKey: 'settings.gitUserEmail.title',
    helpKey: 'settings.gitUserEmail.help',
    placeholderKey: 'settings.gitUserEmail.placeholder',
  }),
]
