import {
  CUSTOM_DOLLIES,
  CUSTOM_ORBITS,
  CUSTOM_PANS,
  FLY_MODES,
  NAVIGATION_PRESETS,
} from './navigationPreset'
import { LANGUAGES } from '../i18n/languages'
import { ASSISTANT_STEPS_MAX, ASSISTANT_STEPS_MIN } from './assistantSteps'
import { DENSITIES, STARTUP_BEHAVIOURS, THEMES } from './settings'
import { setting } from './settingDescriptor'

export const SETTING_REGISTRY_FIRST = [
  setting({
    path: 'general.language',
    kind: 'choice',
    section: 'general',
    titleKey: 'settings.language.title',
    helpKey: 'settings.language.help',
    // A language names itself in its own language, so those labels are not translated — only
    // `system` is. `LANGUAGES` already carries them; a copy in each bundle would be two.
    options: [
      { value: 'system', labelKey: 'settings.language.system' },
      ...LANGUAGES.map(language => ({ value: language.code, label: language.name })),
    ],
  }),
  setting({
    path: 'general.startup',
    kind: 'choice',
    section: 'general',
    titleKey: 'settings.startup.title',
    helpKey: 'settings.startup.help',
    options: STARTUP_BEHAVIOURS.map(behaviour => ({
      value: behaviour,
      labelKey: `settings.startup.${behaviour}`,
    })),
  }),
  setting({
    path: 'general.autosave',
    kind: 'boolean',
    section: 'general',
    titleKey: 'settings.autosave.title',
    helpKey: 'settings.autosave.help',
  }),
  // Beside `startup` rather than in a screen of its own: what shows when the studio opens is
  // one subject. Which sections the home draws, and in which order, is set on the home itself
  // — see `home.sections` in `settingsPath.ts`.
  setting({
    path: 'home.enabled',
    kind: 'boolean',
    section: 'general',
    titleKey: 'settings.home.title',
    helpKey: 'settings.home.help',
  }),
  setting({
    path: 'home.news',
    kind: 'boolean',
    section: 'general',
    titleKey: 'settings.homeNews.title',
    helpKey: 'settings.homeNews.help',
  }),
  setting({
    path: 'appearance.theme',
    kind: 'choice',
    section: 'appearance',
    titleKey: 'settings.theme.title',
    helpKey: 'settings.theme.help',
    // Built from the shared union rather than retyped: one list of themes, read by the screen
    // and by zod alike.
    options: THEMES.map(theme => ({ value: theme, labelKey: `settings.theme.${theme}` })),
  }),
  setting({
    path: 'appearance.density',
    kind: 'choice',
    section: 'appearance',
    titleKey: 'settings.density.title',
    helpKey: 'settings.density.help',
    options: DENSITIES.map(density => ({
      value: density,
      labelKey: `settings.density.${density}`,
    })),
  }),
  setting({
    path: 'appearance.accent',
    kind: 'color',
    section: 'appearance',
    titleKey: 'settings.accent.title',
    helpKey: 'settings.accent.help',
  }),
  setting({
    path: 'appearance.fontScale',
    kind: 'slider',
    section: 'appearance',
    titleKey: 'settings.fontScale.title',
    helpKey: 'settings.fontScale.help',
    min: 0.85,
    max: 1.4,
    step: 0.05,
  }),
  setting({
    path: 'appearance.reduceMotion',
    kind: 'boolean',
    section: 'appearance',
    titleKey: 'settings.reduceMotion.title',
    helpKey: 'settings.reduceMotion.help',
  }),
  setting({
    path: 'assistant.steps',
    kind: 'number',
    section: 'general',
    titleKey: 'settings.assistantSteps.title',
    helpKey: 'settings.assistantSteps.help',
    min: ASSISTANT_STEPS_MIN,
    max: ASSISTANT_STEPS_MAX,
  }),
  setting({
    path: 'generation.concurrentJobs',
    kind: 'number',
    section: 'generation',
    titleKey: 'settings.concurrentJobs.title',
    helpKey: 'settings.concurrentJobs.help',
    min: 1,
    max: 16,
  }),
  setting({
    path: 'generation.maxRetries',
    kind: 'number',
    section: 'generation',
    titleKey: 'settings.maxRetries.title',
    helpKey: 'settings.maxRetries.help',
    min: 0,
    max: 10,
  }),
  setting({
    path: 'generation.landing',
    kind: 'choice',
    section: 'generation',
    titleKey: 'settings.landing.title',
    helpKey: 'settings.landing.help',
    options: [
      { value: 'ask', labelKey: 'settings.landing.ask' },
      { value: 'document', labelKey: 'settings.landing.document' },
      { value: 'newTab', labelKey: 'settings.landing.newTab' },
    ],
  }),
  setting({
    path: 'generation.captionArrivals',
    kind: 'boolean',
    section: 'generation',
    titleKey: 'settings.captionArrivals.title',
    helpKey: 'settings.captionArrivals.help',
  }),
  setting({
    path: 'three.showGrid',
    kind: 'boolean',
    section: 'spaces.three',
    titleKey: 'settings.showGrid.title',
    helpKey: 'settings.showGrid.help',
  }),
  setting({
    path: 'three.gridSize',
    kind: 'number',
    section: 'spaces.three',
    titleKey: 'settings.gridSize.title',
    helpKey: 'settings.gridSize.help',
    min: 2,
    max: 500,
    dependsOn: { path: 'three.showGrid', equals: true },
  }),
  setting({
    path: 'three.navigationPreset',
    kind: 'choice',
    section: 'spaces.three',
    titleKey: 'settings.navigationPreset.title',
    helpKey: 'settings.navigationPreset.help',
    options: NAVIGATION_PRESETS.map(value => ({
      value,
      labelKey: `settings.navigationPreset.${value}`,
    })),
  }),
  setting({
    path: 'three.navigationCustomOrbit',
    kind: 'choice',
    section: 'spaces.three',
    titleKey: 'settings.navigationCustomOrbit.title',
    helpKey: 'settings.navigationCustomOrbit.help',
    options: CUSTOM_ORBITS.map(value => ({
      value,
      labelKey: `settings.navigationCustomOrbit.${value}`,
    })),
    dependsOn: { path: 'three.navigationPreset', equals: 'custom' },
  }),
  setting({
    path: 'three.navigationCustomPan',
    kind: 'choice',
    section: 'spaces.three',
    titleKey: 'settings.navigationCustomPan.title',
    helpKey: 'settings.navigationCustomPan.help',
    options: CUSTOM_PANS.map(value => ({
      value,
      labelKey: `settings.navigationCustomPan.${value}`,
    })),
    dependsOn: { path: 'three.navigationPreset', equals: 'custom' },
  }),
  setting({
    path: 'three.navigationCustomDolly',
    kind: 'choice',
    section: 'spaces.three',
    titleKey: 'settings.navigationCustomDolly.title',
    helpKey: 'settings.navigationCustomDolly.help',
    options: CUSTOM_DOLLIES.map(value => ({
      value,
      labelKey: `settings.navigationCustomDolly.${value}`,
    })),
    dependsOn: { path: 'three.navigationPreset', equals: 'custom' },
  }),
  setting({
    path: 'three.navigationCustomFly',
    kind: 'choice',
    section: 'spaces.three',
    titleKey: 'settings.navigationCustomFly.title',
    helpKey: 'settings.navigationCustomFly.help',
    options: FLY_MODES.map(value => ({ value, labelKey: `settings.navigationCustomFly.${value}` })),
    dependsOn: { path: 'three.navigationPreset', equals: 'custom' },
  }),
  setting({
    path: 'three.orbitAroundSelection',
    kind: 'boolean',
    section: 'spaces.three',
    titleKey: 'settings.orbitAroundSelection.title',
    helpKey: 'settings.orbitAroundSelection.help',
  }),
  setting({
    path: 'three.orbitUnderCursor',
    kind: 'boolean',
    section: 'spaces.three',
    titleKey: 'settings.orbitUnderCursor.title',
    helpKey: 'settings.orbitUnderCursor.help',
  }),
  setting({
    path: 'three.flySpeed',
    kind: 'slider',
    section: 'spaces.three',
    titleKey: 'settings.flySpeed.title',
    helpKey: 'settings.flySpeed.help',
    min: 0.5,
    max: 20,
    step: 0.5,
  }),
  setting({
    path: 'three.boostFactor',
    kind: 'slider',
    section: 'spaces.three',
    titleKey: 'settings.boostFactor.title',
    helpKey: 'settings.boostFactor.help',
    min: 1,
    max: 10,
    step: 0.5,
  }),
  setting({
    path: 'three.fieldOfView',
    kind: 'slider',
    section: 'spaces.three',
    titleKey: 'settings.fieldOfView.title',
    helpKey: 'settings.fieldOfView.help',
    min: 30,
    max: 100,
    step: 5,
  }),
  // Sliders, not counters: a whole-number field refuses the decimals these are made of — their
  // very defaults, half a metre and a tenth, would be unwritable from the screen.
  setting({
    path: 'three.snapTranslate',
    kind: 'slider',
    section: 'spaces.three',
    titleKey: 'settings.snapTranslate.title',
    helpKey: 'settings.snapTranslate.help',
    // Down to a millimetre: the Environment panel offers the fine steps a small object needs,
    // and a floor of a decimetre here would have the write refused on exactly those.
    min: 0.001,
    max: 10,
    step: 0.1,
  }),
]
